use std::{env, net::SocketAddr, sync::Arc};
use auth::{hash_password, issue_token, verify_password, verify_token};
use axum::{extract::{Path, State}, http::{header, HeaderMap, Method, StatusCode}, response::{IntoResponse, Response}, routing::{get, post}, Json, Router};
use serde::{Deserialize, Serialize};
use sqlx::{postgres::PgPoolOptions, PgPool};
use tower_http::{cors::{Any, CorsLayer}, trace::TraceLayer};
use tracing_subscriber::EnvFilter;
use uuid::Uuid;
use validator::Validate;

#[derive(Clone)] struct AppState { db: PgPool, jwt_secret: Arc<str> }
#[derive(Debug)] struct ApiError(StatusCode, String);
impl IntoResponse for ApiError { fn into_response(self) -> Response { (self.0, Json(serde_json::json!({"error": self.1}))).into_response() } }
type ApiResult<T> = Result<Json<T>, ApiError>;
fn bad(message: impl Into<String>) -> ApiError { ApiError(StatusCode::BAD_REQUEST, message.into()) }
fn valid_color(color: &str) -> bool { color.len() == 7 && color.starts_with('#') && color.as_bytes()[1..].iter().all(u8::is_ascii_hexdigit) }
fn forbidden() -> ApiError { ApiError(StatusCode::FORBIDDEN, "forbidden".into()) }
fn internal(e: impl std::fmt::Display) -> ApiError { tracing::error!(error = %e, "request failed"); ApiError(StatusCode::INTERNAL_SERVER_ERROR, "internal server error".into()) }

#[derive(Deserialize, Validate)] struct Credentials { #[validate(email)] email: String, #[validate(length(min = 8, max = 128))] password: String }
#[derive(Deserialize, Validate)] struct Signup { #[validate(email)] email: String, #[validate(length(min = 8, max = 128))] password: String, #[validate(length(min = 1, max = 100))] name: String }
#[derive(Serialize)] struct TokenResponse { access_token: String, token_type: &'static str }
#[derive(Deserialize, Validate)] struct OrganizationInput { #[validate(length(min = 1, max = 100))] name: String, #[validate(length(min = 2, max = 80))] slug: String }
#[derive(Deserialize)] struct MemberInput { user_id: Uuid, role: String }
#[derive(Deserialize, Validate)] struct ProjectInput { organization_id: Uuid, #[validate(length(min = 1, max = 100))] name: String, #[validate(length(min = 2, max = 20))] key: String, #[validate(length(max = 5_000))] description: Option<String> }
#[derive(Deserialize, Validate)] struct ProjectPatch { #[validate(length(min = 1, max = 100))] name: Option<String>, #[validate(length(max = 5_000))] description: Option<String> }
#[derive(Deserialize, Validate)] struct IssueInput { #[validate(length(min = 1, max = 250))] title: String, #[validate(length(max = 20_000))] description: String, status: Option<String>, priority: Option<String>, assignee_id: Option<Uuid> }
#[derive(Deserialize, Validate)] struct IssuePatch { #[validate(length(min = 1, max = 250))] title: Option<String>, #[validate(length(max = 20_000))] description: Option<String>, status: Option<String>, priority: Option<String>, assignee_id: Option<Uuid> }
#[derive(Deserialize, Validate)] struct LabelInput { #[validate(length(min = 1, max = 50))] name: String, color: String }
#[derive(Deserialize)] struct LabelAssignment { label_id: Uuid }

#[derive(Serialize, sqlx::FromRow)] struct Organization { id: Uuid, name: String, slug: String }
#[derive(Serialize, sqlx::FromRow)] struct Project { id: Uuid, organization_id: Uuid, name: String, key: String, description: Option<String> }
#[derive(Serialize, sqlx::FromRow)] struct Issue { id: Uuid, project_id: Uuid, title: String, description: String, status: String, priority: String, assignee_id: Option<Uuid>, reporter_id: Uuid, created_at: chrono::DateTime<chrono::Utc>, updated_at: chrono::DateTime<chrono::Utc> }
#[derive(Serialize, sqlx::FromRow)] struct Label { id: Uuid, project_id: Uuid, name: String, color: String }
#[derive(Serialize, sqlx::FromRow)] struct Membership { user_id: Uuid, role: String }

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    dotenvy::dotenv().ok(); tracing_subscriber::fmt().with_env_filter(EnvFilter::from_default_env()).init();
    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL is required");
    let db = PgPoolOptions::new().max_connections(10).connect(&database_url).await?;
    if env::args().any(|arg| arg == "migrate") { sqlx::migrate!("../../migrations").run(&db).await?; return Ok(()); }
    let state = AppState { db, jwt_secret: env::var("JWT_SECRET").unwrap_or_else(|_| "development-secret-change-me".into()).into() };
    let app = routes(state);
    let address: SocketAddr = env::var("API_ADDR").unwrap_or_else(|_| "0.0.0.0:3001".into()).parse()?;
    tracing::info!(%address, "api listening"); let listener = tokio::net::TcpListener::bind(address).await?; axum::serve(listener, app).await?; Ok(())
}

fn routes(state: AppState) -> Router {
    Router::new().route("/health", get(|| async { StatusCode::NO_CONTENT }))
        .route("/auth/signup", post(signup)).route("/auth/login", post(login)).route("/auth/refresh", post(refresh))
        .route("/organizations", get(list_organizations).post(create_organization)).route("/organizations/:id/members", get(list_org_members).post(add_org_member))
        .route("/projects", get(list_projects).post(create_project)).route("/projects/:id", get(get_project).patch(update_project).delete(delete_project))
        .route("/projects/:id/issues", get(list_issues).post(create_issue)).route("/projects/:id/labels", post(create_label))
        .route("/issues/:id", get(get_issue).patch(update_issue).delete(delete_issue)).route("/issues/:id/labels", post(assign_label))
        .with_state(state).layer(TraceLayer::new_for_http()).layer(CorsLayer::new().allow_origin(Any).allow_methods([Method::GET, Method::POST, Method::PATCH, Method::DELETE]).allow_headers([header::AUTHORIZATION, header::CONTENT_TYPE]))
}

async fn current_user(state: &AppState, headers: &HeaderMap) -> Result<Uuid, ApiError> { let value = headers.get(header::AUTHORIZATION).and_then(|h| h.to_str().ok()).and_then(|h| h.strip_prefix("Bearer ")).ok_or(ApiError(StatusCode::UNAUTHORIZED, "missing bearer token".into()))?; verify_token(value, &state.jwt_secret).map(|c| c.sub).map_err(|_| ApiError(StatusCode::UNAUTHORIZED, "invalid token".into())) }
async fn validate<T: Validate>(input: &T) -> Result<(), ApiError> { input.validate().map_err(|e| bad(e.to_string())) }
async fn project_role(db: &PgPool, user: Uuid, project: Uuid) -> Result<Option<String>, ApiError> { sqlx::query_scalar("SELECT pm.role::text FROM project_members pm WHERE pm.project_id=$1 AND pm.user_id=$2").bind(project).bind(user).fetch_optional(db).await.map_err(internal) }
async fn org_admin(db: &PgPool, user: Uuid, project: Uuid) -> Result<bool, ApiError> { sqlx::query_scalar("SELECT EXISTS(SELECT 1 FROM projects p JOIN organization_members om ON om.organization_id=p.organization_id WHERE p.id=$1 AND om.user_id=$2 AND om.role='admin')").bind(project).bind(user).fetch_one(db).await.map_err(internal) }
#[derive(Clone, Copy)] enum Action { Read, Write, Manage }
fn role_allows(role: Option<&str>, action: Action) -> bool { matches!((role, action), (Some("maintainer"), _) | (Some("developer"), Action::Read | Action::Write) | (Some("reporter"), Action::Read | Action::Write)) }
async fn authorize(state: &AppState, user: Uuid, project: Uuid, action: Action) -> Result<(), ApiError> { if org_admin(&state.db, user, project).await? { return Ok(()); } if role_allows(project_role(&state.db, user, project).await?.as_deref(), action) { Ok(()) } else { Err(forbidden()) } }

async fn signup(State(state): State<AppState>, Json(input): Json<Signup>) -> ApiResult<TokenResponse> { validate(&input).await?; let hash = hash_password(&input.password).map_err(internal)?; let id: Uuid = sqlx::query_scalar("INSERT INTO users (email,password_hash,name) VALUES ($1,$2,$3) RETURNING id").bind(input.email.to_lowercase()).bind(hash).bind(input.name).fetch_one(&state.db).await.map_err(|e| if e.to_string().contains("unique") { bad("email already registered") } else { internal(e) })?; Ok(Json(TokenResponse { access_token: issue_token(id, &state.jwt_secret, 1).map_err(internal)?, token_type: "Bearer" })) }
async fn login(State(state): State<AppState>, Json(input): Json<Credentials>) -> ApiResult<TokenResponse> { validate(&input).await?; let user: Option<(Uuid, String)> = sqlx::query_as("SELECT id,password_hash FROM users WHERE email=$1").bind(input.email.to_lowercase()).fetch_optional(&state.db).await.map_err(internal)?; let (id, hash) = user.ok_or(ApiError(StatusCode::UNAUTHORIZED, "invalid credentials".into()))?; verify_password(&input.password, &hash).map_err(|_| ApiError(StatusCode::UNAUTHORIZED, "invalid credentials".into()))?; Ok(Json(TokenResponse { access_token: issue_token(id, &state.jwt_secret, 1).map_err(internal)?, token_type: "Bearer" })) }
async fn refresh(State(state): State<AppState>, headers: HeaderMap) -> ApiResult<TokenResponse> { let user = current_user(&state, &headers).await?; Ok(Json(TokenResponse { access_token: issue_token(user, &state.jwt_secret, 1).map_err(internal)?, token_type: "Bearer" })) }

async fn list_organizations(State(state): State<AppState>, headers: HeaderMap) -> ApiResult<Vec<Organization>> { let user=current_user(&state,&headers).await?; Ok(Json(sqlx::query_as("SELECT o.id,o.name,o.slug FROM organizations o JOIN organization_members m ON m.organization_id=o.id WHERE m.user_id=$1 ORDER BY o.name").bind(user).fetch_all(&state.db).await.map_err(internal)?)) }
async fn create_organization(State(state): State<AppState>, headers: HeaderMap, Json(input): Json<OrganizationInput>) -> ApiResult<Organization> { let user=current_user(&state,&headers).await?; validate(&input).await?; let mut tx=state.db.begin().await.map_err(internal)?; let org: Organization=sqlx::query_as("INSERT INTO organizations (name,slug) VALUES ($1,$2) RETURNING id,name,slug").bind(input.name).bind(input.slug).fetch_one(&mut *tx).await.map_err(internal)?; sqlx::query("INSERT INTO organization_members (organization_id,user_id,role) VALUES ($1,$2,'admin')").bind(org.id).bind(user).execute(&mut *tx).await.map_err(internal)?; tx.commit().await.map_err(internal)?; Ok(Json(org)) }
async fn list_org_members(State(state): State<AppState>, headers: HeaderMap, Path(id): Path<Uuid>) -> ApiResult<Vec<Membership>> { let user=current_user(&state,&headers).await?; let member: bool=sqlx::query_scalar("SELECT EXISTS(SELECT 1 FROM organization_members WHERE organization_id=$1 AND user_id=$2)").bind(id).bind(user).fetch_one(&state.db).await.map_err(internal)?; if !member{return Err(forbidden())}; Ok(Json(sqlx::query_as("SELECT user_id,role::text AS role FROM organization_members WHERE organization_id=$1").bind(id).fetch_all(&state.db).await.map_err(internal)?)) }
async fn add_org_member(State(state): State<AppState>, headers: HeaderMap, Path(id): Path<Uuid>, Json(input): Json<MemberInput>) -> ApiResult<Membership> { let user=current_user(&state,&headers).await?; let role: Option<String>=sqlx::query_scalar("SELECT role::text FROM organization_members WHERE organization_id=$1 AND user_id=$2").bind(id).bind(user).fetch_optional(&state.db).await.map_err(internal)?; if !matches!(role.as_deref(),Some("admin")|Some("manager")){return Err(forbidden())}; if !matches!(input.role.as_str(),"admin"|"manager"|"member"){return Err(bad("invalid organization role"))}; let m: Membership=sqlx::query_as("INSERT INTO organization_members (organization_id,user_id,role) VALUES ($1,$2,$3::organization_role) ON CONFLICT (organization_id,user_id) DO UPDATE SET role=EXCLUDED.role RETURNING user_id,role::text AS role").bind(id).bind(input.user_id).bind(input.role).fetch_one(&state.db).await.map_err(internal)?; Ok(Json(m)) }

async fn list_projects(State(state): State<AppState>, headers: HeaderMap) -> ApiResult<Vec<Project>> { let user=current_user(&state,&headers).await?; Ok(Json(sqlx::query_as("SELECT DISTINCT p.id,p.organization_id,p.name,p.key,p.description FROM projects p LEFT JOIN project_members pm ON pm.project_id=p.id LEFT JOIN organization_members om ON om.organization_id=p.organization_id WHERE pm.user_id=$1 OR om.user_id=$1 ORDER BY p.name").bind(user).fetch_all(&state.db).await.map_err(internal)?)) }
async fn create_project(State(state): State<AppState>, headers: HeaderMap, Json(input): Json<ProjectInput>) -> ApiResult<Project> { let user=current_user(&state,&headers).await?; validate(&input).await?; let org_role: Option<String>=sqlx::query_scalar("SELECT role::text FROM organization_members WHERE organization_id=$1 AND user_id=$2").bind(input.organization_id).bind(user).fetch_optional(&state.db).await.map_err(internal)?; if !matches!(org_role.as_deref(),Some("admin")|Some("manager")){return Err(forbidden())}; let mut tx=state.db.begin().await.map_err(internal)?; let project:Project=sqlx::query_as("INSERT INTO projects (organization_id,name,key,description) VALUES ($1,$2,$3,$4) RETURNING id,organization_id,name,key,description").bind(input.organization_id).bind(input.name).bind(input.key.to_uppercase()).bind(input.description).fetch_one(&mut *tx).await.map_err(internal)?; sqlx::query("INSERT INTO project_members (project_id,user_id,role) VALUES ($1,$2,'maintainer')").bind(project.id).bind(user).execute(&mut *tx).await.map_err(internal)?; tx.commit().await.map_err(internal)?; Ok(Json(project)) }
async fn get_project(State(state): State<AppState>, headers: HeaderMap, Path(id): Path<Uuid>) -> ApiResult<Project> { let user=current_user(&state,&headers).await?; authorize(&state,user,id,Action::Read).await?; let project=sqlx::query_as("SELECT id,organization_id,name,key,description FROM projects WHERE id=$1").bind(id).fetch_optional(&state.db).await.map_err(internal)?.ok_or(ApiError(StatusCode::NOT_FOUND,"project not found".into()))?; Ok(Json(project)) }
async fn update_project(State(state): State<AppState>, headers: HeaderMap, Path(id): Path<Uuid>, Json(input): Json<ProjectPatch>) -> ApiResult<Project> { let user=current_user(&state,&headers).await?; validate(&input).await?; authorize(&state,user,id,Action::Manage).await?; let project=sqlx::query_as("UPDATE projects SET name=COALESCE($2,name),description=COALESCE($3,description),updated_at=now() WHERE id=$1 RETURNING id,organization_id,name,key,description").bind(id).bind(input.name).bind(input.description).fetch_optional(&state.db).await.map_err(internal)?.ok_or(ApiError(StatusCode::NOT_FOUND,"project not found".into()))?; Ok(Json(project)) }
async fn delete_project(State(state): State<AppState>, headers: HeaderMap, Path(id): Path<Uuid>) -> Result<StatusCode,ApiError> { let user=current_user(&state,&headers).await?; authorize(&state,user,id,Action::Manage).await?; let result=sqlx::query("DELETE FROM projects WHERE id=$1").bind(id).execute(&state.db).await.map_err(internal)?; if result.rows_affected()==0 { Err(ApiError(StatusCode::NOT_FOUND,"project not found".into())) } else { Ok(StatusCode::NO_CONTENT) } }

async fn list_issues(State(state): State<AppState>, headers: HeaderMap, Path(project): Path<Uuid>) -> ApiResult<Vec<Issue>> { let user=current_user(&state,&headers).await?; authorize(&state,user,project,Action::Read).await?; Ok(Json(sqlx::query_as("SELECT id,project_id,title,description,status::text AS status,priority::text AS priority,assignee_id,reporter_id,created_at,updated_at FROM issues WHERE project_id=$1 ORDER BY updated_at DESC").bind(project).fetch_all(&state.db).await.map_err(internal)?)) }
async fn create_issue(State(state): State<AppState>, headers: HeaderMap, Path(project): Path<Uuid>, Json(input): Json<IssueInput>) -> ApiResult<Issue> { let user=current_user(&state,&headers).await?; validate(&input).await?; authorize(&state,user,project,Action::Write).await?; let status=input.status.unwrap_or_else(||"open".into()); let priority=input.priority.unwrap_or_else(||"medium".into()); if !matches!(status.as_str(),"open"|"in_progress"|"closed")||!matches!(priority.as_str(),"low"|"medium"|"high"|"urgent"){return Err(bad("invalid issue status or priority"))}; let issue=sqlx::query_as("INSERT INTO issues (project_id,title,description,status,priority,assignee_id,reporter_id) VALUES ($1,$2,$3,$4::issue_status,$5::issue_priority,$6,$7) RETURNING id,project_id,title,description,status::text AS status,priority::text AS priority,assignee_id,reporter_id,created_at,updated_at").bind(project).bind(input.title).bind(input.description).bind(status).bind(priority).bind(input.assignee_id).bind(user).fetch_one(&state.db).await.map_err(internal)?; Ok(Json(issue)) }
async fn get_issue(State(state): State<AppState>, headers: HeaderMap, Path(id): Path<Uuid>) -> ApiResult<Issue> { let user=current_user(&state,&headers).await?; let issue:Issue=sqlx::query_as("SELECT id,project_id,title,description,status::text AS status,priority::text AS priority,assignee_id,reporter_id,created_at,updated_at FROM issues WHERE id=$1").bind(id).fetch_optional(&state.db).await.map_err(internal)?.ok_or(ApiError(StatusCode::NOT_FOUND,"issue not found".into()))?; authorize(&state,user,issue.project_id,Action::Read).await?; Ok(Json(issue)) }
async fn update_issue(State(state): State<AppState>, headers: HeaderMap, Path(id): Path<Uuid>, Json(input): Json<IssuePatch>) -> ApiResult<Issue> { let user=current_user(&state,&headers).await?; validate(&input).await?; let existing: (Uuid,)=sqlx::query_as("SELECT project_id FROM issues WHERE id=$1").bind(id).fetch_optional(&state.db).await.map_err(internal)?.ok_or(ApiError(StatusCode::NOT_FOUND,"issue not found".into()))?; authorize(&state,user,existing.0,Action::Write).await?; if input.status.as_deref().is_some_and(|v|!matches!(v,"open"|"in_progress"|"closed"))||input.priority.as_deref().is_some_and(|v|!matches!(v,"low"|"medium"|"high"|"urgent")){return Err(bad("invalid issue status or priority"))}; let issue=sqlx::query_as("UPDATE issues SET title=COALESCE($2,title),description=COALESCE($3,description),status=COALESCE($4::issue_status,status),priority=COALESCE($5::issue_priority,priority),assignee_id=COALESCE($6,assignee_id),updated_at=now() WHERE id=$1 RETURNING id,project_id,title,description,status::text AS status,priority::text AS priority,assignee_id,reporter_id,created_at,updated_at").bind(id).bind(input.title).bind(input.description).bind(input.status).bind(input.priority).bind(input.assignee_id).fetch_one(&state.db).await.map_err(internal)?; Ok(Json(issue)) }
async fn delete_issue(State(state): State<AppState>, headers: HeaderMap, Path(id): Path<Uuid>) -> Result<StatusCode,ApiError> { let user=current_user(&state,&headers).await?; let project: (Uuid,)=sqlx::query_as("SELECT project_id FROM issues WHERE id=$1").bind(id).fetch_optional(&state.db).await.map_err(internal)?.ok_or(ApiError(StatusCode::NOT_FOUND,"issue not found".into()))?; authorize(&state,user,project.0,Action::Write).await?; sqlx::query("DELETE FROM issues WHERE id=$1").bind(id).execute(&state.db).await.map_err(internal)?; Ok(StatusCode::NO_CONTENT) }
async fn create_label(State(state): State<AppState>, headers: HeaderMap, Path(project): Path<Uuid>, Json(input): Json<LabelInput>) -> ApiResult<Label> { let user=current_user(&state,&headers).await?; validate(&input).await?; if !valid_color(&input.color) { return Err(bad("color must be a #RRGGBB value")); } authorize(&state,user,project,Action::Write).await?; Ok(Json(sqlx::query_as("INSERT INTO labels (project_id,name,color) VALUES ($1,$2,$3) RETURNING id,project_id,name,color").bind(project).bind(input.name).bind(input.color).fetch_one(&state.db).await.map_err(internal)?)) }
async fn assign_label(State(state): State<AppState>, headers: HeaderMap, Path(issue): Path<Uuid>, Json(input): Json<LabelAssignment>) -> Result<StatusCode,ApiError> { let user=current_user(&state,&headers).await?; let project: (Uuid,)=sqlx::query_as("SELECT project_id FROM issues WHERE id=$1").bind(issue).fetch_optional(&state.db).await.map_err(internal)?.ok_or(ApiError(StatusCode::NOT_FOUND,"issue not found".into()))?; authorize(&state,user,project.0,Action::Write).await?; let valid:bool=sqlx::query_scalar("SELECT EXISTS(SELECT 1 FROM labels WHERE id=$1 AND project_id=$2)").bind(input.label_id).bind(project.0).fetch_one(&state.db).await.map_err(internal)?; if !valid{return Err(bad("label is not part of this project"))}; sqlx::query("INSERT INTO issue_labels (issue_id,label_id) VALUES ($1,$2) ON CONFLICT DO NOTHING").bind(issue).bind(input.label_id).execute(&state.db).await.map_err(internal)?; Ok(StatusCode::NO_CONTENT) }

#[cfg(test)]
mod tests {
    use super::{role_allows, Action};
    #[test]
    fn project_role_permissions() {
        assert!(role_allows(Some("maintainer"), Action::Manage));
        assert!(role_allows(Some("developer"), Action::Write));
        assert!(role_allows(Some("reporter"), Action::Read));
        assert!(!role_allows(Some("developer"), Action::Manage));
        assert!(!role_allows(Some("reporter"), Action::Manage));
        assert!(!role_allows(None, Action::Read));
    }
}
